//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte settings_screen_resolution_id {
            get {
                return ((byte)(this["settings_screen_resolution_id"]));
            }
            set {
                this["settings_screen_resolution_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_other_is_vignette {
            get {
                return ((bool)(this["settings_other_is_vignette"]));
            }
            set {
                this["settings_other_is_vignette"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_interface_is_dungeon_level {
            get {
                return ((bool)(this["settings_interface_is_dungeon_level"]));
            }
            set {
                this["settings_interface_is_dungeon_level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_interface_is_minimap {
            get {
                return ((bool)(this["settings_interface_is_minimap"]));
            }
            set {
                this["settings_interface_is_minimap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_interface_is_potions {
            get {
                return ((bool)(this["settings_interface_is_potions"]));
            }
            set {
                this["settings_interface_is_potions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_interface_is_stats {
            get {
                return ((bool)(this["settings_interface_is_stats"]));
            }
            set {
                this["settings_interface_is_stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys settings_controls_move_up {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_move_up"]));
            }
            set {
                this["settings_controls_move_up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys settings_controls_move_down {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_move_down"]));
            }
            set {
                this["settings_controls_move_down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys settings_controls_move_left {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_move_left"]));
            }
            set {
                this["settings_controls_move_left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys settings_controls_move_right {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_move_right"]));
            }
            set {
                this["settings_controls_move_right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public global::System.Windows.Forms.Keys settings_controls_inventory {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_inventory"]));
            }
            set {
                this["settings_controls_inventory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public global::System.Windows.Forms.Keys settings_controls_statistic {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_statistic"]));
            }
            set {
                this["settings_controls_statistic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public global::System.Windows.Forms.Keys settings_controls_map {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_map"]));
            }
            set {
                this["settings_controls_map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::System.Windows.Forms.Keys settings_controls_action_pickup_item {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_action_pickup_item"]));
            }
            set {
                this["settings_controls_action_pickup_item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::System.Windows.Forms.Keys settings_controls_action_hit {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_action_hit"]));
            }
            set {
                this["settings_controls_action_hit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public global::System.Windows.Forms.Keys settings_controls_use_potion_1 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_use_potion_1"]));
            }
            set {
                this["settings_controls_use_potion_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public global::System.Windows.Forms.Keys settings_controls_use_potion_2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_use_potion_2"]));
            }
            set {
                this["settings_controls_use_potion_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public global::System.Windows.Forms.Keys settings_controls_use_potion_3 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_use_potion_3"]));
            }
            set {
                this["settings_controls_use_potion_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::System.Windows.Forms.Keys settings_controls_open_ingame_menu {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_open_ingame_menu"]));
            }
            set {
                this["settings_controls_open_ingame_menu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_other_is_blood_effect_on_hit {
            get {
                return ((bool)(this["settings_other_is_blood_effect_on_hit"]));
            }
            set {
                this["settings_other_is_blood_effect_on_hit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public global::System.Windows.Forms.Keys settings_controls_item_use {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_item_use"]));
            }
            set {
                this["settings_controls_item_use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public global::System.Windows.Forms.Keys settings_controls_item_drop {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_item_drop"]));
            }
            set {
                this["settings_controls_item_drop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys settings_controls_item_destroy {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_item_destroy"]));
            }
            set {
                this["settings_controls_item_destroy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::System.Windows.Forms.Keys settings_controls_choose_up {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_choose_up"]));
            }
            set {
                this["settings_controls_choose_up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::System.Windows.Forms.Keys settings_controls_choose_down {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_choose_down"]));
            }
            set {
                this["settings_controls_choose_down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.Keys settings_controls_choose_left {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_choose_left"]));
            }
            set {
                this["settings_controls_choose_left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.Forms.Keys settings_controls_choose_right {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_choose_right"]));
            }
            set {
                this["settings_controls_choose_right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public global::System.Windows.Forms.Keys settings_controls_item_info {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_item_info"]));
            }
            set {
                this["settings_controls_item_info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte settings_audio_volume_sound {
            get {
                return ((byte)(this["settings_audio_volume_sound"]));
            }
            set {
                this["settings_audio_volume_sound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte settings_audio_volume_music {
            get {
                return ((byte)(this["settings_audio_volume_music"]));
            }
            set {
                this["settings_audio_volume_music"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_interface_is_hero_level {
            get {
                return ((bool)(this["settings_interface_is_hero_level"]));
            }
            set {
                this["settings_interface_is_hero_level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settings_interface_is_buttons {
            get {
                return ((bool)(this["settings_interface_is_buttons"]));
            }
            set {
                this["settings_interface_is_buttons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::System.Windows.Forms.Keys settings_controls_game_save {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_game_save"]));
            }
            set {
                this["settings_controls_game_save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public global::System.Windows.Forms.Keys settings_controls_game_load {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_game_load"]));
            }
            set {
                this["settings_controls_game_load"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public global::System.Windows.Forms.Keys settings_controls_hide_interface {
            get {
                return ((global::System.Windows.Forms.Keys)(this["settings_controls_hide_interface"]));
            }
            set {
                this["settings_controls_hide_interface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settings_other_is_autosave {
            get {
                return ((bool)(this["settings_other_is_autosave"]));
            }
            set {
                this["settings_other_is_autosave"] = value;
            }
        }
    }
}
